// "use client"
import './globals.css';

import type { Metadata } from 'next';
import { Inter, MuseoModerno, Poppins } from 'next/font/google';
import Link from 'next/link';
import { useRouter } from 'next/navigation';

import Toast from '@/components/Toast';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
});

const museoModerno = MuseoModerno({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '600', '700'],
  variable: '--font-museo-moderno',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
<html
  lang='id, en'
  className={`${inter.variable} ${poppins.variable} ${museoModerno.variable}`}
>
  <body>
    <Toast />
    {children}
  </body>
</html>

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   // buat router push

//   const router = useRouter();
//   const onClickUrl = (url: string) => {
//     router.push(url);
//   };

//   return (
//     <html>
//       <body>
//         {children}
//         <div>Footer</div>
//       </body>
//     </html>
  );
}
